/**
 * @file Hand-written Candid IDL factory and TypeScript types for the **Gateway** canister.
 *
 * Normally these bindings would be auto-generated by `dfx generate` or `@icp-sdk/bindgen`,
 * but because OpenClaw uses a custom build pipeline the IDL is maintained by hand.
 * If the canister's `.did` file changes, this file must be updated to match.
 *
 * ## Candid-to-JavaScript type mapping conventions
 *
 * | Candid          | JavaScript / IDL helper           | TypeScript mirror                        |
 * |-----------------|-----------------------------------|------------------------------------------|
 * | `variant { A; B }` | `IDL.Variant({ A: IDL.Null, B: IDL.Null })` | `{ A: null } \| { B: null }`     |
 * | `opt T`         | `IDL.Opt(T)`                      | `[] \| [T]` (empty array = none)         |
 * | `vec nat8`      | `IDL.Vec(IDL.Nat8)`               | `Uint8Array \| number[]`                 |
 * | `record { ... }`| `IDL.Record({ ... })`             | `interface { ... }`                      |
 * | `nat` / `int`   | `IDL.Nat` / `IDL.Int`             | `bigint`                                 |
 *
 * @module api/gateway.did
 */

import { IDL } from "@icp-sdk/core/candid";
import { Actor, HttpAgent, type ActorSubclass } from "@icp-sdk/core/agent";
import { Principal } from "@icp-sdk/core/principal";
import { GATEWAY_CANISTER_ID } from "./agent";

// ── Candid types ────────────────────────────────────────────────────

/** Message author role: system prompt, human user, or AI assistant. */
const Role = IDL.Variant({
  system_: IDL.Null,
  user: IDL.Null,
  assistant: IDL.Null,
});

/**
 * External (off-chain) LLM models that require an API key.
 * The gateway canister proxies HTTPS outcalls to the provider's API.
 */
const ExternalModel = IDL.Variant({
  Claude_Sonnet: IDL.Null,
  Claude_Haiku: IDL.Null,
  GPT4o: IDL.Null,
  GPT4oMini: IDL.Null,
  MagickMind_Brain: IDL.Null,
});

/**
 * On-chain LLM models that run inference directly on the Internet Computer.
 * These do not require an API key but consume cycles.
 */
const OnChainModel = IDL.Variant({
  Llama3_1_8B: IDL.Null,
  Llama4Scout: IDL.Null,
  Qwen3_32B: IDL.Null,
});

/** Top-level model discriminator: on-chain vs. external. */
const Model = IDL.Variant({
  External: ExternalModel,
  OnChain: OnChainModel,
});

/** Opaque conversation identifier (a text UUID). */
const ConversationId = IDL.Text;

/** A single chat message with a role and text content. */
const Message = IDL.Record({
  role: Role,
  content: IDL.Text,
});

/** Full conversation object including all messages and timestamps. */
const Conversation = IDL.Record({
  id: ConversationId,
  owner: IDL.Principal,
  model: Model,
  messages: IDL.Vec(Message),
  createdAt: IDL.Int,
  updatedAt: IDL.Int,
  mindspaceId: IDL.Opt(IDL.Text),
});

/** Lightweight conversation metadata returned by `listConversations`. */
const ConversationSummary = IDL.Record({
  id: ConversationId,
  model: Model,
  messageCount: IDL.Nat,
  updatedAt: IDL.Int,
  title: IDL.Text,
  preview: IDL.Text,
  mindspaceId: IDL.Opt(IDL.Text),
});

/** Export format discriminator for `exportConversation`. */
const ExportFormat = IDL.Variant({
  JSON: IDL.Null,
  Markdown: IDL.Null,
});

/**
 * Request payload sent to the `prompt` method.
 *
 * - `conversationId`: `[]` to start a new conversation, `[id]` to continue one.
 * - `systemPrompt`: optional system-level instruction prepended to context.
 * - `apiKey`: optional API key override (normally retrieved from KeyVault on-chain).
 */
const PromptRequest = IDL.Record({
  message: IDL.Text,
  model: Model,
  conversationId: IDL.Opt(ConversationId),
  systemPrompt: IDL.Opt(IDL.Text),
  apiKey: IDL.Opt(IDL.Text),
  mindspaceId: IDL.Opt(IDL.Text),
});

/** Successful response from the `prompt` method. */
const PromptResponse = IDL.Record({
  reply: IDL.Text,
  conversationId: ConversationId,
  model: Model,
  tokensUsed: IDL.Opt(IDL.Nat),
  mindspaceId: IDL.Opt(IDL.Text),
});

/** Exhaustive error variant returned by gateway canister methods. */
const OpenClawError = IDL.Variant({
  NotAuthenticated: IDL.Null,
  ConversationNotFound: IDL.Null,
  AlreadyProcessing: IDL.Null,
  InsufficientBalance: IDL.Null,
  CycleBudgetExceeded: IDL.Null,
  ResponseTooLarge: IDL.Null,
  Timeout: IDL.Null,
  InvalidInput: IDL.Text,
  ApiKeyNotFound: IDL.Text,
  WalletError: IDL.Text,
  ProviderError: IDL.Text,
});

/** Successful response from the `dualPrompt` method (fast + smart replies). */
const DualPromptResponse = IDL.Record({
  conversationId: ConversationId,
  fastReply: IDL.Text,
  smartReply: IDL.Text,
  model: Model,
  mindspaceId: IDL.Opt(IDL.Text),
});

/** Result type for `dualPrompt`. */
const DualPromptResult = IDL.Variant({
  ok: DualPromptResponse,
  err: OpenClawError,
});

/** Request payload for the `compareModels` method. */
const CompareRequest = IDL.Record({
  message: IDL.Text,
  modelIds: IDL.Vec(IDL.Text),
  conversationId: IDL.Opt(IDL.Text),
  systemPrompt: IDL.Opt(IDL.Text),
  mindspaceId: IDL.Opt(IDL.Text),
});

/** A single model's response in a compare result. */
const ModelResponse = IDL.Record({
  modelId: IDL.Text,
  reply: IDL.Text,
});

/** Successful response from the `compareModels` method. */
const CompareResponse = IDL.Record({
  conversationId: IDL.Text,
  responses: IDL.Vec(ModelResponse),
});

/** Result type for `compareModels`. */
const CompareResult = IDL.Variant({
  ok: CompareResponse,
  err: OpenClawError,
});

/** Result type for `prompt` — success returns a {@link PromptResponse}. */
const Result = IDL.Variant({ ok: PromptResponse, err: OpenClawError });
/** Result type for `listConversations`. */
const Result_1 = IDL.Variant({
  ok: IDL.Vec(ConversationSummary),
  err: OpenClawError,
});
/** Result type for `getConversation`. */
const Result_2 = IDL.Variant({ ok: Conversation, err: OpenClawError });
/** Result type for `deleteConversation` (ok carries no payload). */
const Result_3 = IDL.Variant({ ok: IDL.Null, err: OpenClawError });

/** A reusable system prompt template (built-in or user-created). */
const SystemPromptTemplate = IDL.Record({
  id: IDL.Text,
  name: IDL.Text,
  content: IDL.Text,
  isBuiltIn: IDL.Bool,
  createdAt: IDL.Int,
});

/** Result type for `saveTemplate`. */
const Result_4 = IDL.Variant({ ok: SystemPromptTemplate, err: OpenClawError });
/** Result type for `listTemplates`. */
const Result_5 = IDL.Variant({ ok: IDL.Vec(SystemPromptTemplate), err: OpenClawError });
/** Result type for `deleteTemplate`. */
const Result_6 = IDL.Variant({ ok: IDL.Null, err: OpenClawError });
/** Result type for `searchConversations`. */
const Result_7 = IDL.Variant({ ok: IDL.Vec(ConversationSummary), err: OpenClawError });
/** Result type for `exportConversation`. */
const Result_8 = IDL.Variant({ ok: IDL.Text, err: OpenClawError });
/** Result type for `getModelFees` — returns an array of (modelKey, fee) tuples. */
const ModelFeesResult = IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat));

/** MagickMind brain mode: Fast (instant) vs Smart (deeper processing). */
const MagickMindBrainMode = IDL.Variant({
  Fast: IDL.Null,
  Smart: IDL.Null,
});

/** MagickMind user configuration: mindspace ID + brain mode + Multi-LLM settings. */
const MagickMindConfig = IDL.Record({
  mindspaceId: IDL.Text,
  brainMode: MagickMindBrainMode,
  fastModelId: IDL.Text,
  smartModelIds: IDL.Vec(IDL.Text),
  computePower: IDL.Nat,
});

/** Result type for `setMagickMindConfig` (ok carries no payload). */
const Result_9 = IDL.Variant({ ok: IDL.Null, err: OpenClawError });
/** Result type for `getMagickMindConfig`. */
const Result_10 = IDL.Variant({ ok: MagickMindConfig, err: OpenClawError });

/** A persona AI personality profile used with MagickMind. */
const Persona = IDL.Record({
  id: IDL.Text,
  name: IDL.Text,
  avatar: IDL.Text,
  description: IDL.Text,
  personality: IDL.Text,
  tone: IDL.Text,
  expertise: IDL.Vec(IDL.Text),
  instructions: IDL.Text,
  isBuiltIn: IDL.Bool,
  createdAt: IDL.Int,
  updatedAt: IDL.Int,
});

/** Result type for `savePersona` / `getPersona`. */
const PersonaResult = IDL.Variant({
  ok: Persona,
  err: OpenClawError,
});

/** Result type for `listPersonas`. */
const PersonaListResult = IDL.Variant({
  ok: IDL.Vec(Persona),
  err: OpenClawError,
});

/** Result type for `compilePersona`. */
const TextResult = IDL.Variant({
  ok: IDL.Text,
  err: OpenClawError,
});

/** Void result reused for deletePersona, inviteToGroupChat, etc. */
const VoidResult = IDL.Variant({ ok: IDL.Null, err: OpenClawError });

// ── Trait types (MagickMind-aligned) ────────────────────────────────

/** Trait value type — matches MagickMind's polymorphic trait system. */
const TraitType = IDL.Variant({
  Numeric: IDL.Null,
  Categorical: IDL.Null,
  Multilabel: IDL.Null,
});

/** Lock level — controls whether a trait can evolve. */
const TraitLock = IDL.Variant({
  Hard: IDL.Null,
  Soft: IDL.Null,
});

/** A single persona trait with full MagickMind-aligned fields. */
const PersonaTrait = IDL.Record({
  name: IDL.Text,
  displayName: IDL.Text,
  traitType: TraitType,
  description: IDL.Text,
  numericValue: IDL.Opt(IDL.Nat),
  categoricalValue: IDL.Opt(IDL.Text),
  multilabelValue: IDL.Vec(IDL.Text),
  options: IDL.Vec(IDL.Text),
  minValue: IDL.Nat,
  maxValue: IDL.Nat,
  defaultValue: IDL.Nat,
  lock: TraitLock,
  learningRate: IDL.Nat,
  supportsDyadic: IDL.Bool,
  category: IDL.Text,
});

/** Growth type — how the persona evolves over time. */
const GrowthType = IDL.Variant({
  Fixed: IDL.Null,
  Expanding: IDL.Null,
  Corrupting: IDL.Null,
  Redeeming: IDL.Null,
  Transcending: IDL.Null,
});

/** Per-domain growth rates. */
const DomainRates = IDL.Record({
  identity: IDL.Nat,
  narrative: IDL.Nat,
  behavior: IDL.Nat,
});

/** Growth trigger — condition that modifies evolution rate. */
const GrowthTrigger = IDL.Record({
  id: IDL.Text,
  condition: IDL.Text,
  affectedTraits: IDL.Vec(IDL.Text),
  rateMultiplier: IDL.Nat,
  direction: IDL.Variant({ TowardTarget: IDL.Null, AwayFromTarget: IDL.Null, Normal: IDL.Null }),
});

/** Goal state — target personality configuration traits are attracted toward. */
const GoalState = IDL.Record({
  id: IDL.Text,
  description: IDL.Text,
  traitTargets: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  attractionStrength: IDL.Nat,
});

/** Boundary — hard limits on trait evolution. */
const TraitBoundary = IDL.Record({
  traitName: IDL.Text,
  minValue: IDL.Nat,
  maxValue: IDL.Nat,
  reason: IDL.Text,
});

/** Full growth configuration for a persona. */
const GrowthConfig = IDL.Record({
  growthType: GrowthType,
  domainRates: DomainRates,
  triggers: IDL.Vec(GrowthTrigger),
  goalStates: IDL.Vec(GoalState),
  boundaries: IDL.Vec(TraitBoundary),
});

/** Multi-LLM configuration for MagickMind's Smart Brain. */
const MultiLlmConfig = IDL.Record({
  fastModelId: IDL.Text,
  smartModelIds: IDL.Vec(IDL.Text),
  computePower: IDL.Nat,
});

/** A snapshot of traits at a point in time, for evolution history. */
const TraitSnapshot = IDL.Record({
  traits: IDL.Vec(PersonaTrait),
  timestamp: IDL.Int,
  trigger: IDL.Text,
});

/** Full persona traits record including growth config and evolution state. */
const PersonaTraits = IDL.Record({
  personaId: IDL.Text,
  traits: IDL.Vec(PersonaTrait),
  growthConfig: GrowthConfig,
  multiLlmConfig: IDL.Opt(MultiLlmConfig),
  evolutionHistory: IDL.Vec(TraitSnapshot),
  lastEvolvedAt: IDL.Int,
});

/** Result type for persona traits operations. */
const PersonaTraitsResult = IDL.Variant({
  ok: PersonaTraits,
  err: OpenClawError,
});

/** Turn order strategy for group chat. */
const TurnOrder = IDL.Variant({
  RoundRobin: IDL.Null,
  Facilitator: IDL.Text,
  FreeForm: IDL.Null,
});

/** A group chat with multiple personas. */
const GroupChat = IDL.Record({
  id: IDL.Text,
  name: IDL.Text,
  personaIds: IDL.Vec(IDL.Text),
  turnOrder: TurnOrder,
  facilitatorId: IDL.Opt(IDL.Text),
  invitedUsers: IDL.Vec(IDL.Principal),
  createdAt: IDL.Int,
  updatedAt: IDL.Int,
});

/** Result type for group chat operations. */
const GroupChatResult = IDL.Variant({
  ok: GroupChat,
  err: OpenClawError,
});

/** Result type for listing group chats. */
const GroupChatListResult = IDL.Variant({
  ok: IDL.Vec(GroupChat),
  err: OpenClawError,
});

/** A message in a group chat, attributed to a persona or user. */
const GroupMessage = IDL.Record({
  role: Role,
  content: IDL.Text,
  personaId: IDL.Opt(IDL.Text),
  personaName: IDL.Opt(IDL.Text),
  personaAvatar: IDL.Opt(IDL.Text),
  targetPersonaId: IDL.Opt(IDL.Text),
  senderPrincipal: IDL.Opt(IDL.Principal),
});

/** Request payload for group chat prompt. */
const GroupPromptRequest = IDL.Record({
  groupId: IDL.Text,
  conversationId: IDL.Opt(IDL.Text),
  message: IDL.Text,
  mindspaceId: IDL.Opt(IDL.Text),
  targetPersonaId: IDL.Opt(IDL.Text),
});

/** Response from a group chat prompt containing all persona responses. */
const GroupPromptResponse = IDL.Record({
  conversationId: IDL.Text,
  responses: IDL.Vec(GroupMessage),
});

/** Result type for group prompt. */
const GroupPromptResult = IDL.Variant({
  ok: GroupPromptResponse,
  err: OpenClawError,
});

/** Result of a communication operation (email/SMS send). */
const CommResult = IDL.Variant({
  Sent: IDL.Text,
  Failed: IDL.Text,
  NotConfigured: IDL.Text,
});

/** Result of a memory operation (corpus/pelican/mindspace). */
const MemoryResult = IDL.Variant({
  Success: IDL.Text,
  Failed: IDL.Text,
  NotConfigured: IDL.Text,
});

// ── Marketplace IDL Types ────────────────────────────────────────────

const PaymentType = IDL.Variant({ PerMessage: IDL.Null, Daily: IDL.Null });
const MarketplaceCategory = IDL.Variant({
  All: IDL.Null, Code: IDL.Null, Research: IDL.Null,
  Creative: IDL.Null, Business: IDL.Null, Coaching: IDL.Null,
  Custom: IDL.Text,
});

const PublishedPersona = IDL.Record({
  owner: IDL.Principal, personaId: IDL.Text, personaName: IDL.Text,
  personaDescription: IDL.Text, pricePerMessage: IDL.Nat, pricePerDay: IDL.Nat,
  totalEarnings: IDL.Nat, hireCount: IDL.Nat, ratingSum: IDL.Nat,
  ratingCount: IDL.Nat, corpusIds: IDL.Vec(IDL.Text),
  category: MarketplaceCategory, isActive: IDL.Bool, publishedAt: IDL.Int,
});

const PersonaHire = IDL.Record({
  hirer: IDL.Principal, personaId: IDL.Text, owner: IDL.Principal,
  paymentType: PaymentType, expiresAt: IDL.Int, messagesUsed: IDL.Nat,
  totalPaid: IDL.Nat, startedAt: IDL.Int,
});

const PersonaNftMetadata = IDL.Record({
  personaId: IDL.Text, owner: IDL.Principal,
  traitSnapshot: IDL.Vec(PersonaTrait), corpusRefs: IDL.Vec(IDL.Text),
  mintedAt: IDL.Int, tokenId: IDL.Nat,
});

const MarketplaceListing = IDL.Record({
  published: PublishedPersona, traitCount: IDL.Nat, averageRating: IDL.Nat,
});

const MarketplaceOpResult = IDL.Variant({ Ok: IDL.Text, Err: IDL.Text });

// ── IDL factory ─────────────────────────────────────────────────────

/**
 * Candid IDL factory for the Gateway canister.
 *
 * This function is passed to {@link Actor.createActor} and describes the
 * canister's public interface so the agent can encode/decode Candid payloads.
 */
export const idlFactory: IDL.InterfaceFactory = ({ IDL: _IDL }) => {
  return IDL.Service({
    prompt: IDL.Func([PromptRequest], [Result], []),
    dualPrompt: IDL.Func([PromptRequest], [DualPromptResult], []),
    compareModels: IDL.Func([CompareRequest], [CompareResult], []),
    getConversation: IDL.Func([ConversationId], [Result_2], ["query"]),
    listConversations: IDL.Func([], [Result_1], ["query"]),
    deleteConversation: IDL.Func([ConversationId], [Result_3], []),
    saveTemplate: IDL.Func([IDL.Text, IDL.Text], [Result_4], []),
    listTemplates: IDL.Func([], [Result_5], ["query"]),
    deleteTemplate: IDL.Func([IDL.Text], [Result_6], []),
    searchConversations: IDL.Func([IDL.Text], [Result_7], ["query"]),
    exportConversation: IDL.Func([ConversationId, ExportFormat], [Result_8], ["query"]),
    getModelFees: IDL.Func([], [ModelFeesResult], ["query"]),
    sendEmail: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [CommResult], []),
    sendSms: IDL.Func([IDL.Text, IDL.Text], [CommResult], []),
    setMagickMindConfig: IDL.Func([IDL.Text, MagickMindBrainMode, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat], [Result_9], []),
    getMagickMindConfig: IDL.Func([], [Result_10], ["query"]),
    savePersona: IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [PersonaResult],
      []
    ),
    listPersonas: IDL.Func([], [PersonaListResult], ['query']),
    getPersona: IDL.Func([IDL.Text], [PersonaResult], ['query']),
    deletePersona: IDL.Func([IDL.Text], [VoidResult], []),
    compilePersona: IDL.Func([IDL.Text], [TextResult], ['query']),
    getPersonaTraits: IDL.Func([IDL.Text], [PersonaTraitsResult], ['query']),
    savePersonaTraits: IDL.Func([IDL.Text, IDL.Vec(PersonaTrait), GrowthConfig, IDL.Opt(MultiLlmConfig)], [PersonaTraitsResult], []),
    evolvePersonaTraits: IDL.Func([IDL.Text, IDL.Text], [PersonaTraitsResult], []),
    createGroupChat: IDL.Func([IDL.Text, IDL.Vec(IDL.Text), TurnOrder], [GroupChatResult], []),
    listGroupChats: IDL.Func([], [GroupChatListResult], ['query']),
    deleteGroupChat: IDL.Func([IDL.Text], [VoidResult], []),
    groupPrompt: IDL.Func([GroupPromptRequest], [GroupPromptResult], []),
    inviteToGroupChat: IDL.Func([IDL.Text, IDL.Principal], [VoidResult], []),
    queryCorpus: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [MemoryResult], []),
    prepareContext: IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [MemoryResult], []),
    createCorpus: IDL.Func([IDL.Text, IDL.Text], [MemoryResult], []),
    listCorpora: IDL.Func([], [MemoryResult], []),
    deleteCorpus: IDL.Func([IDL.Text], [MemoryResult], []),
    presignUpload: IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)], [MemoryResult], []),
    addArtifactToCorpus: IDL.Func([IDL.Text, IDL.Text], [MemoryResult], []),
    getIngestionStatus: IDL.Func([IDL.Text, IDL.Text], [MemoryResult], []),
    listMindspaces: IDL.Func([], [MemoryResult], []),
    createMindspace: IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text], [MemoryResult], []),
    // Persona API
    'mmPreparePersona': IDL.Func([IDL.Text], [MemoryResult], []),
    'mmListPersonaVersions': IDL.Func([IDL.Text], [MemoryResult], []),
    'mmGetActivePersonaVersion': IDL.Func([IDL.Text], [MemoryResult], []),
    'mmGetEffectivePersonality': IDL.Func([IDL.Text], [MemoryResult], []),
    // Blueprint & Traits API
    'mmListBlueprints': IDL.Func([], [MemoryResult], []),
    'mmGetBlueprintByKey': IDL.Func([IDL.Text], [MemoryResult], []),
    'mmHydrateBlueprint': IDL.Func([IDL.Text], [MemoryResult], []),
    'mmListTraits': IDL.Func([], [MemoryResult], []),
    // Message History & Participants
    'mmGetMessages': IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [MemoryResult], []),
    'mmAddParticipant': IDL.Func([IDL.Text, IDL.Text, IDL.Text], [MemoryResult], []),
    'mmCreatePersonaFromBlueprint': IDL.Func([IDL.Text, IDL.Text, IDL.Text], [MemoryResult], []),
    'mmInvalidateCache': IDL.Func([], [MemoryResult], []),
    // Marketplace
    publishPersona: IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), MarketplaceCategory], [MarketplaceOpResult], []),
    unpublishPersona: IDL.Func([IDL.Text], [MarketplaceOpResult], []),
    browseMarketplace: IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [IDL.Vec(MarketplaceListing)], []),
    hirePersona: IDL.Func([IDL.Text, PaymentType], [MarketplaceOpResult], []),
    endHire: IDL.Func([IDL.Text], [MarketplaceOpResult], []),
    listMyHires: IDL.Func([], [IDL.Vec(PersonaHire)], []),
    ratePersona: IDL.Func([IDL.Text, IDL.Nat], [MarketplaceOpResult], []),
    getPersonaEarnings: IDL.Func([IDL.Text], [MarketplaceOpResult], []),
    withdrawPersonaEarnings: IDL.Func([IDL.Text, IDL.Nat], [MarketplaceOpResult], []),
    mintPersonaNft: IDL.Func([IDL.Text], [MarketplaceOpResult], []),
    getPersonaNft: IDL.Func([IDL.Text], [IDL.Opt(PersonaNftMetadata)], []),
    health: IDL.Func([], [IDL.Text], ["query"]),
  });
};

// ── TypeScript types (mirrors the Candid types) ─────────────────────

/** TypeScript mirror of the Candid `Role` variant. */
export type CandidRole = { system_: null } | { user: null } | { assistant: null };

/**
 * TypeScript mirror of the Candid `ExternalModel` variant.
 * Each key is a model identifier; the `null` value is the Candid convention for
 * unit variants (no associated data).
 */
export type CandidExternalModel =
  | { Claude_Sonnet: null }
  | { Claude_Haiku: null }
  | { GPT4o: null }
  | { GPT4oMini: null }
  | { MagickMind_Brain: null };

/** TypeScript mirror of the Candid `OnChainModel` variant. */
export type CandidOnChainModel =
  | { Llama3_1_8B: null }
  | { Llama4Scout: null }
  | { Qwen3_32B: null };

/**
 * Top-level model discriminator.
 * Exactly one key (`External` or `OnChain`) will be present in any given value.
 */
export type CandidModel =
  | { External: CandidExternalModel }
  | { OnChain: CandidOnChainModel };

/**
 * TypeScript interface for the `PromptRequest` Candid record.
 *
 * Optional Candid fields (`opt T`) are represented as `[] | [T]`:
 * - `[]` means "none" (absent).
 * - `[value]` means "some" (present).
 */
export interface CandidPromptRequest {
  message: string;
  model: CandidModel;
  /** Empty array to start a new conversation, or `[id]` to continue one. */
  conversationId: [] | [string];
  /** Optional system prompt prepended to the conversation context. */
  systemPrompt: [] | [string];
  /** Optional API key; if omitted the canister retrieves it from KeyVault. */
  apiKey: [] | [string];
  /** Optional MagickMind mindspace ID for this conversation. */
  mindspaceId: [] | [string];
}

/** TypeScript interface for the `PromptResponse` Candid record. */
export interface CandidPromptResponse {
  reply: string;
  conversationId: string;
  model: CandidModel;
  /** Token usage count, if the provider reports it. */
  tokensUsed: [] | [bigint];
  /** MagickMind mindspace ID associated with this response, if any. */
  mindspaceId: [] | [string];
}

/** TypeScript interface for the `DualPromptResponse` Candid record. */
export interface CandidDualPromptResponse {
  conversationId: string;
  fastReply: string;
  smartReply: string;
  model: CandidModel;
  mindspaceId: [] | [string];
}

/** TypeScript interface for a single model response in a compare result. */
export interface CandidModelResponse {
  modelId: string;
  reply: string;
}

/** TypeScript interface for the `CompareResponse` Candid record. */
export interface CandidCompareResponse {
  conversationId: string;
  responses: CandidModelResponse[];
}

/** Union of all possible error variants returned by the gateway. */
export type CandidOpenClawError =
  | { NotAuthenticated: null }
  | { ConversationNotFound: null }
  | { AlreadyProcessing: null }
  | { CycleBudgetExceeded: null }
  | { ResponseTooLarge: null }
  | { Timeout: null }
  | { InvalidInput: string }
  | { ApiKeyNotFound: string }
  | { ProviderError: string };

/**
 * Generic Candid Result type.
 * Check for `"ok" in result` to narrow to the success case.
 *
 * @typeParam T - The payload type on success.
 */
export type CandidResult<T> = { ok: T } | { err: CandidOpenClawError };

/** TypeScript mirror of the Candid `SystemPromptTemplate` record. */
export interface CandidSystemPromptTemplate {
  id: string;
  name: string;
  content: string;
  isBuiltIn: boolean;
  createdAt: bigint;
}

/** TypeScript mirror of the Candid `MagickMindBrainMode` variant. */
export type CandidMagickMindBrainMode = { Fast: null } | { Smart: null };

/** TypeScript mirror of the Candid `MagickMindConfig` record. */
export interface CandidMagickMindConfig {
  mindspaceId: string;
  brainMode: CandidMagickMindBrainMode;
  fastModelId: string;
  smartModelIds: string[];
  computePower: bigint;
}

/** TypeScript mirror of the Candid `Persona` record. */
export interface CandidPersona {
  id: string;
  name: string;
  avatar: string;
  description: string;
  personality: string;
  tone: string;
  expertise: string[];
  instructions: string;
  isBuiltIn: boolean;
  createdAt: bigint;
  updatedAt: bigint;
}

/** TypeScript mirror of the Candid `ExportFormat` variant. */
export type CandidExportFormat = { JSON: null } | { Markdown: null };

/** TypeScript mirror of the Candid `CommResult` variant. */
export type CandidCommResult =
  | { Sent: string }
  | { Failed: string }
  | { NotConfigured: string };

/** TypeScript mirror of the Candid `MemoryResult` variant. */
export type CandidMemoryResult = { Success: string } | { Failed: string } | { NotConfigured: string };

// ── Marketplace TypeScript Types ──────────────────────────────────

export type CandidPaymentType = { PerMessage: null } | { Daily: null };
export type CandidMarketplaceCategory = { All: null } | { Code: null } | { Research: null } | { Creative: null } | { Business: null } | { Coaching: null } | { Custom: string };
export type CandidMarketplaceOpResult = { Ok: string } | { Err: string };

export interface CandidPublishedPersona {
  owner: Principal;
  personaId: string;
  personaName: string;
  personaDescription: string;
  pricePerMessage: bigint;
  pricePerDay: bigint;
  totalEarnings: bigint;
  hireCount: bigint;
  ratingSum: bigint;
  ratingCount: bigint;
  corpusIds: string[];
  category: CandidMarketplaceCategory;
  isActive: boolean;
  publishedAt: bigint;
}

export interface CandidPersonaHire {
  hirer: Principal;
  personaId: string;
  owner: Principal;
  paymentType: CandidPaymentType;
  expiresAt: bigint;
  messagesUsed: bigint;
  totalPaid: bigint;
  startedAt: bigint;
}

export interface CandidPersonaNftMetadata {
  personaId: string;
  owner: Principal;
  traitSnapshot: CandidPersonaTrait[];
  corpusRefs: string[];
  mintedAt: bigint;
  tokenId: bigint;
}

export interface CandidMarketplaceListing {
  published: CandidPublishedPersona;
  traitCount: bigint;
  averageRating: bigint;
}

// ── Trait types ──────────────────────────────────────────────────────

/** TypeScript mirror of the Candid `TraitType` variant. */
export type CandidTraitType = { Numeric: null } | { Categorical: null } | { Multilabel: null };

/** TypeScript mirror of the Candid `TraitLock` variant. */
export type CandidTraitLock = { Hard: null } | { Soft: null };

/** TypeScript mirror of the Candid `PersonaTrait` record (MagickMind-aligned). */
export interface CandidPersonaTrait {
  name: string;
  displayName: string;
  traitType: CandidTraitType;
  description: string;
  numericValue: [] | [bigint];
  categoricalValue: [] | [string];
  multilabelValue: string[];
  options: string[];
  minValue: bigint;
  maxValue: bigint;
  defaultValue: bigint;
  lock: CandidTraitLock;
  learningRate: bigint;
  supportsDyadic: boolean;
  category: string;
}

/** TypeScript mirror of the Candid `GrowthType` variant. */
export type CandidGrowthType = { Fixed: null } | { Expanding: null } | { Corrupting: null } | { Redeeming: null } | { Transcending: null };

/** TypeScript mirror of the Candid `DomainRates` record. */
export interface CandidDomainRates {
  identity: bigint;
  narrative: bigint;
  behavior: bigint;
}

/** TypeScript mirror of the Candid `GrowthTrigger` record. */
export interface CandidGrowthTrigger {
  id: string;
  condition: string;
  affectedTraits: string[];
  rateMultiplier: bigint;
  direction: { TowardTarget: null } | { AwayFromTarget: null } | { Normal: null };
}

/** TypeScript mirror of the Candid `GoalState` record. */
export interface CandidGoalState {
  id: string;
  description: string;
  traitTargets: [string, bigint][];
  attractionStrength: bigint;
}

/** TypeScript mirror of the Candid `TraitBoundary` record. */
export interface CandidTraitBoundary {
  traitName: string;
  minValue: bigint;
  maxValue: bigint;
  reason: string;
}

/** TypeScript mirror of the Candid `GrowthConfig` record. */
export interface CandidGrowthConfig {
  growthType: CandidGrowthType;
  domainRates: CandidDomainRates;
  triggers: CandidGrowthTrigger[];
  goalStates: CandidGoalState[];
  boundaries: CandidTraitBoundary[];
}

/** TypeScript mirror of the Candid `MultiLlmConfig` record. */
export interface CandidMultiLlmConfig {
  fastModelId: string;
  smartModelIds: string[];
  computePower: bigint;
}

/** TypeScript mirror of the Candid `TraitSnapshot` record. */
export interface CandidTraitSnapshot {
  traits: CandidPersonaTrait[];
  timestamp: bigint;
  trigger: string;
}

/** TypeScript mirror of the Candid `PersonaTraits` record. */
export interface CandidPersonaTraits {
  personaId: string;
  traits: CandidPersonaTrait[];
  growthConfig: CandidGrowthConfig;
  multiLlmConfig: [] | [CandidMultiLlmConfig];
  evolutionHistory: CandidTraitSnapshot[];
  lastEvolvedAt: bigint;
}

/** TypeScript mirror of the Candid `TurnOrder` variant. */
export type CandidTurnOrder = { RoundRobin: null } | { Facilitator: string } | { FreeForm: null };

/** TypeScript mirror of the Candid `GroupChat` record. */
export interface CandidGroupChat {
  id: string;
  name: string;
  personaIds: string[];
  turnOrder: CandidTurnOrder;
  facilitatorId: [] | [string];
  invitedUsers: Principal[];
  createdAt: bigint;
  updatedAt: bigint;
}

/** TypeScript mirror of the Candid `GroupMessage` record. */
export interface CandidGroupMessage {
  role: Record<string, null>;
  content: string;
  personaId: [] | [string];
  personaName: [] | [string];
  personaAvatar: [] | [string];
  targetPersonaId: [] | [string];
  senderPrincipal: [] | [Principal];
}

/** TypeScript mirror of the Candid `GroupPromptResponse` record. */
export interface CandidGroupPromptResponse {
  conversationId: string;
  responses: CandidGroupMessage[];
}

/** TypeScript mirror of the Candid `ConversationSummary` record. */
export interface CandidConversationSummary {
  id: string;
  model: CandidModel;
  messageCount: bigint;
  updatedAt: bigint;
  title: string;
  preview: string;
  /** MagickMind mindspace ID, if this conversation uses one. */
  mindspaceId: [] | [string];
}

/**
 * Strongly-typed service interface for the Gateway canister actor.
 * Used as the generic parameter to {@link Actor.createActor}.
 */
export interface GatewayService {
  /** Send a user message and get an AI reply. Update call (goes through consensus). */
  prompt: (req: CandidPromptRequest) => Promise<CandidResult<CandidPromptResponse>>;
  /** Send a dual prompt and get both fast and smart replies. Update call. */
  dualPrompt: (req: CandidPromptRequest) => Promise<{ ok: CandidDualPromptResponse } | { err: Record<string, unknown> }>;
  /** Send the same prompt to multiple models and compare responses. Update call. */
  compareModels: (req: { message: string; modelIds: string[]; conversationId: [] | [string]; systemPrompt: [] | [string]; mindspaceId: [] | [string] }) => Promise<{ ok: CandidCompareResponse } | { err: Record<string, unknown> }>;
  /** Fetch full conversation including all messages. Query call (fast, no consensus). */
  getConversation: (id: string) => Promise<CandidResult<unknown>>;
  /** List conversation summaries for the authenticated caller. */
  listConversations: () => Promise<CandidResult<unknown[]>>;
  /** Delete a conversation by ID. Requires ownership. */
  deleteConversation: (id: string) => Promise<CandidResult<null>>;
  /** Save a new system prompt template. Returns the created template. */
  saveTemplate: (name: string, content: string) => Promise<CandidResult<CandidSystemPromptTemplate>>;
  /** List all system prompt templates (built-in + user-created). */
  listTemplates: () => Promise<CandidResult<CandidSystemPromptTemplate[]>>;
  /** Delete a user-created template by ID. Built-in templates cannot be deleted. */
  deleteTemplate: (templateId: string) => Promise<CandidResult<null>>;
  /** Search conversations by message content (case-insensitive). */
  searchConversations: (query: string) => Promise<CandidResult<CandidConversationSummary[]>>;
  /** Export a conversation in JSON or Markdown format. */
  exportConversation: (convId: string, format: CandidExportFormat) => Promise<CandidResult<string>>;
  /** Query per-model fee overrides. Returns (modelKey, fee) tuples. */
  getModelFees: () => Promise<[string, bigint][]>;
  /** Send an email via Resend. Requires resend_api_key in KeyVault. */
  sendEmail: (to: string, subject: string, htmlBody: string, from: [] | [string]) => Promise<CandidCommResult>;
  /** Send an SMS via Twilio. Requires twilio credentials in KeyVault. */
  sendSms: (to: string, body: string) => Promise<CandidCommResult>;
  /** Save MagickMind configuration (mindspace + brain mode + Multi-LLM). Update call. */
  setMagickMindConfig: (mindspaceId: string, brainMode: CandidMagickMindBrainMode, fastModelId: string, smartModelIds: string[], computePower: bigint) => Promise<CandidResult<null>>;
  /** Get the caller's MagickMind configuration. Query call. */
  getMagickMindConfig: () => Promise<CandidResult<CandidMagickMindConfig>>;
  /** Save or update a persona. Pass [] for new, [id] to update. */
  savePersona: (
    personaId: [] | [string],
    name: string,
    avatar: string,
    description: string,
    personality: string,
    tone: string,
    expertise: string[],
    instructions: string
  ) => Promise<{ ok: CandidPersona } | { err: Record<string, unknown> }>;
  /** List all personas (built-in + user-created). */
  listPersonas: () => Promise<{ ok: CandidPersona[] } | { err: Record<string, unknown> }>;
  /** Get a single persona by ID. */
  getPersona: (id: string) => Promise<{ ok: CandidPersona } | { err: Record<string, unknown> }>;
  /** Delete a user-created persona by ID. */
  deletePersona: (id: string) => Promise<{ ok: null } | { err: Record<string, unknown> }>;
  /** Compile a persona into a system prompt string. */
  compilePersona: (id: string) => Promise<{ ok: string } | { err: Record<string, unknown> }>;
  /** Get persona traits including growth config and evolution state. */
  getPersonaTraits: (personaId: string) => Promise<{ ok: CandidPersonaTraits } | { err: Record<string, unknown> }>;
  /** Save persona traits with growth config and optional Multi-LLM config. */
  savePersonaTraits: (personaId: string, traits: CandidPersonaTrait[], growthConfig: CandidGrowthConfig, multiLlmConfig: [] | [CandidMultiLlmConfig]) => Promise<{ ok: CandidPersonaTraits } | { err: Record<string, unknown> }>;
  /** Trigger trait evolution based on conversation summary. */
  evolvePersonaTraits: (personaId: string, summary: string) => Promise<{ ok: CandidPersonaTraits } | { err: Record<string, unknown> }>;
  /** Create a new group chat with selected personas and turn order. */
  createGroupChat: (name: string, personaIds: string[], turnOrder: CandidTurnOrder) => Promise<{ ok: CandidGroupChat } | { err: Record<string, unknown> }>;
  /** List all group chats for the caller. */
  listGroupChats: () => Promise<{ ok: CandidGroupChat[] } | { err: Record<string, unknown> }>;
  /** Delete a group chat by ID. */
  deleteGroupChat: (id: string) => Promise<{ ok: null } | { err: Record<string, unknown> }>;
  /** Send a message to a group chat, receiving responses from all personas (or targeted persona). */
  groupPrompt: (req: { groupId: string; conversationId: [] | [string]; message: string; mindspaceId: [] | [string]; targetPersonaId: [] | [string] }) => Promise<{ ok: CandidGroupPromptResponse } | { err: Record<string, unknown> }>;
  /** Invite a human user (by Principal) to a group chat. */
  inviteToGroupChat: (groupId: string, invitee: Principal) => Promise<{ ok: null } | { err: Record<string, unknown> }>;
  /** Query a corpus with semantic search. */
  queryCorpus: (corpusId: string, query: string, mode: string, onlyContext: boolean) => Promise<CandidMemoryResult>;
  /** Compose chat history + corpus + pelican into unified context. */
  prepareContext: (mindspaceId: string, historyLimit: bigint, corpusQuery: [] | [string], pelicanQuery: [] | [string]) => Promise<CandidMemoryResult>;
  /** Create a new knowledge base corpus. */
  createCorpus: (name: string, description: string) => Promise<CandidMemoryResult>;
  /** List all corpora for the authenticated user. */
  listCorpora: () => Promise<CandidMemoryResult>;
  /** Delete a corpus by ID. */
  deleteCorpus: (corpusId: string) => Promise<CandidMemoryResult>;
  /** Get a presigned S3 upload URL for a file. */
  presignUpload: (fileName: string, contentType: string, sizeBytes: bigint, corpusId: [] | [string]) => Promise<CandidMemoryResult>;
  /** Add an uploaded artifact to a corpus for ingestion. */
  addArtifactToCorpus: (corpusId: string, artifactId: string) => Promise<CandidMemoryResult>;
  /** Get the ingestion status of an artifact in a corpus. */
  getIngestionStatus: (corpusId: string, artifactId: string) => Promise<CandidMemoryResult>;
  /** List all mindspaces for the authenticated user. */
  listMindspaces: () => Promise<CandidMemoryResult>;
  /** Create a new mindspace. */
  createMindspace: (name: string, description: string, corpusIds: string[], msType: string) => Promise<CandidMemoryResult>;
  /** Prepare a MagickMind persona for use. */
  mmPreparePersona: (personaId: string) => Promise<CandidMemoryResult>;
  /** List all versions of a MagickMind persona. */
  mmListPersonaVersions: (personaId: string) => Promise<CandidMemoryResult>;
  /** Get the active version of a MagickMind persona. */
  mmGetActivePersonaVersion: (personaId: string) => Promise<CandidMemoryResult>;
  /** Get the effective (runtime-blended) personality for a persona. */
  mmGetEffectivePersonality: (personaId: string) => Promise<CandidMemoryResult>;
  /** List all available persona blueprints. */
  mmListBlueprints: () => Promise<CandidMemoryResult>;
  /** Get a blueprint by its key. */
  mmGetBlueprintByKey: (key: string) => Promise<CandidMemoryResult>;
  /** Hydrate a blueprint to see full trait definitions. */
  mmHydrateBlueprint: (blueprintId: string) => Promise<CandidMemoryResult>;
  /** List all server-side traits. */
  mmListTraits: () => Promise<CandidMemoryResult>;
  /** Get paginated messages from a mindspace. */
  mmGetMessages: (mindspaceId: string, limit: bigint, order: string, cursor: [] | [string]) => Promise<CandidMemoryResult>;
  /** Add a participant to a mindspace. */
  mmAddParticipant: (mindspaceId: string, userId: string, role: string) => Promise<CandidMemoryResult>;
  /** Create a new persona from a blueprint. */
  mmCreatePersonaFromBlueprint: (blueprintId: string, name: string, description: string) => Promise<CandidMemoryResult>;
  /** Invalidate the MagickMind runtime cache. */
  mmInvalidateCache: () => Promise<CandidMemoryResult>;
  // Marketplace
  publishPersona: (personaId: string, pricePerMessage: bigint, pricePerDay: bigint, corpusIds: string[], category: CandidMarketplaceCategory) => Promise<CandidMarketplaceOpResult>;
  unpublishPersona: (personaId: string) => Promise<CandidMarketplaceOpResult>;
  browseMarketplace: (category: string, sortBy: string, offset: bigint, limit: bigint) => Promise<CandidMarketplaceListing[]>;
  hirePersona: (personaId: string, paymentType: CandidPaymentType) => Promise<CandidMarketplaceOpResult>;
  endHire: (personaId: string) => Promise<CandidMarketplaceOpResult>;
  listMyHires: () => Promise<CandidPersonaHire[]>;
  ratePersona: (personaId: string, rating: bigint) => Promise<CandidMarketplaceOpResult>;
  getPersonaEarnings: (personaId: string) => Promise<CandidMarketplaceOpResult>;
  withdrawPersonaEarnings: (personaId: string, amount: bigint) => Promise<CandidMarketplaceOpResult>;
  mintPersonaNft: (personaId: string) => Promise<CandidMarketplaceOpResult>;
  getPersonaNft: (personaId: string) => Promise<[] | [CandidPersonaNftMetadata]>;
  /** Canister health check. Returns a status string. */
  health: () => Promise<string>;
}

// ── Actor helper ────────────────────────────────────────────────────

/**
 * Create a typed actor for the Gateway canister.
 *
 * @param agent - An authenticated {@link HttpAgent} (from {@link createAgent}).
 * @param canisterId - Optional override; defaults to the build-time `VITE_GATEWAY_CANISTER_ID`.
 * @returns An {@link ActorSubclass} typed to {@link GatewayService}.
 *
 * @example
 * ```ts
 * const agent = await createAgent(authClient);
 * const gateway = createGatewayActor(agent);
 * const result = await gateway.prompt({ ... });
 * ```
 */
export function createGatewayActor(
  agent: HttpAgent,
  canisterId?: string,
): ActorSubclass<GatewayService> {
  return Actor.createActor<GatewayService>(idlFactory, {
    agent,
    canisterId: canisterId ?? GATEWAY_CANISTER_ID,
  });
}
