/**
 * @file Hand-written Candid IDL factory and TypeScript types for the **KeyVault** canister.
 *
 * The KeyVault canister has two responsibilities:
 *
 * 1. **vetKD key derivation** — Exposes `getVetkeyVerificationKey` and
 *    `getEncryptedVetkey` so the frontend can derive per-user AES-256-GCM
 *    encryption keys via the ICP vetKD (Verifiable Encrypted Threshold Key
 *    Derivation) protocol. See {@link ../vetkeys.ts} for the client-side flow.
 *
 * 2. **Encrypted key storage** — Stores and retrieves opaque blobs (typically
 *    AES-GCM ciphertext of API keys) keyed by `(caller principal, keyId)`.
 *    The canister never sees plaintext API keys; encryption/decryption happens
 *    entirely on the client.
 *
 * Like {@link ./gateway.did.ts}, this file is maintained by hand. See that
 * module's header for the Candid-to-JS type mapping conventions.
 *
 * @module api/keyvault.did
 */

import { IDL } from "@icp-sdk/core/candid";
import { Actor, HttpAgent, type ActorSubclass } from "@icp-sdk/core/agent";
import { KEYVAULT_CANISTER_ID } from "./agent";

// ── Candid IDL ──────────────────────────────────────────────────

/** Generic success/error result with no payload on success. */
const Result = IDL.Variant({ ok: IDL.Null, err: IDL.Text });
/** Success/error result where the success payload is a byte blob. */
const ResultBlob = IDL.Variant({ ok: IDL.Vec(IDL.Nat8), err: IDL.Text });

/**
 * Candid IDL factory for the KeyVault canister.
 *
 * Methods:
 * - `getVetkeyVerificationKey` — Return the canister's vetKD verification
 *   (public) key bytes. Used to verify that the encrypted vetKey came from ICP
 *   threshold signing. Update call (requires consensus to produce the key).
 * - `getEncryptedVetkey` — Accept a transport public key and return the
 *   caller's encrypted vetKey. Only the holder of the matching transport
 *   secret key can decrypt it. Update call.
 * - `storeEncryptedKey` — Persist an encrypted blob under `(caller, keyId)`.
 * - `getEncryptedKey` — Retrieve a stored blob by `(principal, keyId)`.
 * - `hasKey` — Check if a key exists for the caller (query, fast).
 * - `deleteKey` — Remove a stored key.
 * - `health` — Liveness check.
 */
export const idlFactory: IDL.InterfaceFactory = ({ IDL: _IDL }) => {
  return IDL.Service({
    // vetKD key derivation
    getVetkeyVerificationKey: IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    getEncryptedVetkey: IDL.Func([IDL.Vec(IDL.Nat8)], [ResultBlob], []),
    // Key storage
    storeEncryptedKey: IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [Result], []),
    getEncryptedKey: IDL.Func([IDL.Principal, IDL.Text], [ResultBlob], []),
    hasKey: IDL.Func([IDL.Text], [IDL.Bool], ["query"]),
    deleteKey: IDL.Func([IDL.Text], [Result], []),
    health: IDL.Func([], [IDL.Text], ["query"]),
  });
};

// ── TypeScript types ────────────────────────────────────────────

/** Result with no success payload. Check `"ok" in result` to discriminate. */
export type KeyVaultResult = { ok: null } | { err: string };

/** Result carrying a byte blob on success (e.g. an encrypted key or vetKey). */
export type KeyVaultBlobResult = { ok: Uint8Array | number[] } | { err: string };

/**
 * Strongly-typed service interface for the KeyVault canister actor.
 */
export interface KeyVaultService {
  /**
   * Fetch the canister's vetKD verification (public) key.
   * Used client-side to verify the authenticity of the encrypted vetKey.
   */
  getVetkeyVerificationKey: () => Promise<Uint8Array | number[]>;

  /**
   * Request an encrypted vetKey for the caller.
   * @param transportPubKey - The ephemeral transport public key generated by
   *   {@link TransportSecretKey.random}. The canister encrypts the vetKey to
   *   this public key so only the session holder can decrypt it.
   */
  getEncryptedVetkey: (transportPubKey: Uint8Array | number[]) => Promise<KeyVaultBlobResult>;

  /**
   * Store an encrypted blob (e.g. an AES-GCM-encrypted API key).
   * @param keyId - Logical key name, e.g. `"anthropic_api_key"`.
   * @param blob - The ciphertext bytes to store.
   */
  storeEncryptedKey: (keyId: string, blob: Uint8Array | number[]) => Promise<KeyVaultResult>;

  /**
   * Check whether a key with the given ID exists for the caller.
   * This is a query call (fast, no consensus).
   */
  hasKey: (keyId: string) => Promise<boolean>;

  /**
   * Delete a stored key by its logical ID.
   * @param keyId - The key name to delete.
   */
  deleteKey: (keyId: string) => Promise<KeyVaultResult>;

  /** Canister health check. */
  health: () => Promise<string>;
}

// ── Actor helper ────────────────────────────────────────────────

/**
 * Create a typed actor for the KeyVault canister.
 *
 * @param agent - An authenticated {@link HttpAgent} (from {@link createAgent}).
 * @param canisterId - Optional override; defaults to `VITE_KEYVAULT_CANISTER_ID`.
 * @returns An {@link ActorSubclass} typed to {@link KeyVaultService}.
 */
export function createKeyVaultActor(
  agent: HttpAgent,
  canisterId?: string,
): ActorSubclass<KeyVaultService> {
  return Actor.createActor<KeyVaultService>(idlFactory, {
    agent,
    canisterId: canisterId ?? KEYVAULT_CANISTER_ID,
  });
}
